### ISSUE TITLE
Wrong unit for KNX Sensor Type "wind_speed_ms" applied

### ISSUE THREAD

**Issue by PaRe1803** [XKNX/knx-integration#10]
I have added a sensor for wind speed, which is measured in [m/s]:

KNX:
![image](https://github.com/user-attachments/assets/f30c5470-8f4d-4ae6-b9aa-9bc2da5130c5)

YAML:
![image](https://github.com/user-attachments/assets/10198ee3-1c35-4c08-8958-ab9572a7b7d3)

Unfortunately, the created entity unit is [km/h] instead of [m/s]:
![image](https://github.com/user-attachments/assets/435e51be-d18a-489b-b103-21bc36f14b53)

Did I do something wrong or is this an issue in the KNX integration of Home Assistant?

**Comment by farmio** [comment]
Hi 👋! 
Since `device_class` is correct, you should be able to change the unit in the entity options menu.

**Comment by PaRe1803** [comment]
Hi @farmio,

thanks for your fast reply and suggestion.

You mean in dev.tools -> entities -> change the unit_of_measurement to "m/s" and Set State?
![image](https://github.com/user-attachments/assets/de5a92af-d2e8-4dfe-b3eb-52f048dbe863)

I tried this already and it temporarily worked, but after a system restart the change is gone.

Any other suggestions?

**Comment by farmio** [comment]
No, I mean the settings found in the "more info" dialog of the entity.
<img width="603" alt="Bildschirmfoto 2024-11-08 um 12 35 19" src="https://github.com/user-attachments/assets/aba72e1b-49ee-483f-aedb-010c0918b7ab">

**Comment by PaRe1803** [comment]
You are right, this worked. THANKS for your very fast support!

Anyhow - it is weird that the wrong unit is taken as the Default unit, isn't it?

**Comment by farmio** [comment]
It's using the default unit - probably based on location or user selection, I don't know for sure. Anyway, that's independent of backend / integration unit.

**Comment by PaRe1803** [comment]
Sorry farmio, but I think I have to disagree, because there are different DPT values types for each unit:
![image](https://github.com/user-attachments/assets/dd043f62-e3a6-44c8-ac5e-b2101a09ac3c)

![image](https://github.com/user-attachments/assets/96b7976f-3416-4e71-94ff-82c44504f3e2)

**Comment by farmio** [comment]
It's a HA (maybe user) default. Knx is the backend - that determines only `native_unit_of_measurement` (although I don't think that property is user facing).
