### ISSUE TITLE
KNX "Respond to read" - wrong response adress for status GA

### ISSUE THREAD

**Issue by IllegalDuke** [XKNX/knx-integration#16]
Hello,

I recognized, that the option "Respond to read" in the GUI for a switch entity is not working as intended.
I set up group adress "1/0/7 - L_K02_02 E/A (Wandlicht Kellerraum)" as actor/switching adress for sending commands by physical KNX push-buttons and "1/0/8 - L_K02_02 R/M (Wandlicht Kellerraum)" as status group adress for the feedback from actor after switching to the physical knx push buttons.

So normally a KNX-actor ist reading the 1/0/7 switching group adress, switches the ligth on/off and responses to the 1/0/8 status group adress.

In my case Home Assistant is the connection between knx and shelly. (HASS as bus-master)! That means when a knx push-button wants to switch the light on by sending 1 to the 1/0/7, this will be forwarded by an automation in HASS automation to shelly. When shelly is switched manually, then this will be forwarded by HASS automation to the KNX-bus to the adress 1/0/8 (status of light).
But when a bus device (e.g. push-button) is asking for the status of the light, it will send a GroupValueRead to the 1/0/8. 
In this case, with the option "Respond to read" in the GUI set, HASS will not respond.
When I manually send a GroupValueRead to the 1/0/7 (which makes no sense according KNX rules), HASS would answer this with a GroupValueResponse to 1/0/7.

Can you please fix the logic of "Respond to read" in the GUI .
When no status adress is set, a GroupValueResponse to the main group adress is fine.
If a status adress is set, in all cases I know, the GroupValueRead will come from KNX-bus to the status adress and should be answered by HASS to the status adress.

Until this is fixed, I need to solve this by automations in HASS.

Thank you for your help.

BR
Daniel

**Comment by farmio** [comment]
Hi 👋! 
Related issue: https://github.com/home-assistant/core/issues/84913

Imho using a Knx proxy entity (your switch) to forward 3rd party integrations entity states (your Shelly entity) is not the best design itself. This would be done more elegantly by an automation with `knx.telegram` trigger and (optionally) `expose`. 
I think there are blueprints to be found for that.

**Comment by IllegalDuke** [comment]
Hi,

thank you for your feedback. I have read the related issue and this is similar to mine.

I worked around this and created an automation blueprint with `knx.telegram`  and `knx.send` as interface to shelly with the ability to respond to knx read requests.

From my side this could be closed, even if I think the implemented logic for respond to read for a light or switch entity does not make sense (when state group address is available).
Normally group read requests will be sent to the state address and should then be answered to the state address by this knx interface (when state adress is available).

Thank you and merry christmas :-)

**Comment by farmio** [comment]
I think it is just awkward that those keys / objects use the same wording "state". Other than that it behaves quite similar.

A HA entity never sends any telegram to a `*_state` address - except for a GroupValueRead. If a switch entity is toggled, it sends over its `address`. If you want to know the state of that, you may read it - same address it sends new states to.

A knx actuator on the other hand would send a new state over its `state` called object. Again, read this object if you want to know the current / last state. You wouldn't read the setter-object.

So imho sending new states to `address`, but only responding to `state_address`, would be awkward - a knx state object of something interested in the state of that switch would need to bind to both addresses.

Sending and responding to `address` when there is no `state_address` but sending and responding to `state_address` when there is one would imho lead to even more confusion.

**Comment by IllegalDuke** [comment]
Thank you for your answer. I fully understand you.

As long as HA is acting as a visualization and as timer/automation, this ist fine. Then HA will trigger someting on the bus at the `address` and receive an answer to a `*_state` address.

In my case HA is the bridge to some shellys and other stuff like Vallox ventilation unit or my heatpump. Then the KNX bus will send a trigger by a push-button to HA to the `address`. HA will then work with this trigger, forward it to my devices (e.g. heatpump) and answer to the `*_state` address.

I thought the "Respond to read" could be used for the regular update to the knx bus, when the knx devices are asking for a status update.

Nevermind, with an automation this was easily implemented and I generated a blueprint to use this for all my KNX-addresses where HA is the bus master (acting like a knx actuator).

Only remaining question is, if I can deactivate the initial read to the knx bus for a switch or light entity with `sync_state`, because it is not described in the HA documentation. Right now HA is reading its own state, because no other device on the KNX bus will answer the read requests.

Thank you for your help!

**Comment by farmio** [comment]
> if I can deactivate the initial read to the knx bus for a switch or light entity with sync_state, because it is not described in the HA documentation

No. It would be documented if this was an option. 
You can however just not set a `state_address`. 

> because no other device on the KNX bus will answer the read requests

HA Knx entities are representations of Knx functions in HA. It's generally better to use actions and triggers to couple 3rd party entities.

**Comment by IllegalDuke** [comment]
Thank you for your help.

I will close this issue.
