### ISSUE TITLE
DataSecure / Keyfile issues rendering unusable group addresses

### ISSUE THREAD

**Issue by indivliving** [XKNX/knx-integration#2]
I have linked my new Home Assistant and new KNX installation with each other via KNX Secure. This worked without any problems. But the more devices I added, the more problems arose.
- Sometimes it takes up to 5 minutes for responses to come from the KNX bus. But sometimes immediately
- Some addresses do not respond at all
- No recognizable pattern

The KNX project was created with ETS 6.2.1 and Home Assistant runs on 2024.3.3.

The following message is repeated in the log.

Could not decrypt CEMI frame: Discarding frame with plain APDU for secure group address: CEMILData(src_addr="IndividualAddress("1.1.33")" dst_addr="GroupAddress("6/0/1")" flags="1011110011010000" tpci="TDataGroup()" payload="<GroupValueWrite value="<DPTBinary value="0" />" />") 

I have already done several KNX <-> home assistant installations, so far always without problems.

**Comment by farmio** [comment]
Hi 👋! 
> Some addresses do not respond at all

is very related to the error log you posted here. 
When xknx / HA is expecting a group address to be DataSecure (in the example 6/0/1) it ignores non-secure telegrams received for that GA. 
Vice versa, if HA sends encrypted telegrams and the receiving devices expect them to be plain, they can't handle them.

This is probably a result of an outdated (or currupted) `.knxkeys` file.

**Comment by indivliving** [comment]
Thanks for your quick reply.
mhh okay? the GA 6/0/1 was never a secure device. 
I fixed it for now. I load a "new" (the same which i used all the time) .knxkeys file, reboot the system and for now the errors are gone.
I think the operation could be a little easier. Or an "unload" button for the keys files. 
The way I see it, things are being changed somewhere in the background that affect Secure even though no changes are made to the keys themselves.

**Comment by farmio** [comment]
How could it be designed this to be easier? (apart from a "delete keyfile" button - which in a DataSecure using installation would also render some GAs unusable, but I still agree that this should be added)

> The way I see it, things are being changed somewhere in the background that affect Secure even though no changes are made to the keys themselves.

Well, the keyfile is read and loaded every single restart of the knx integration / HA. I would be surprised if the internal data structure it is loaded to was changed on runtime - you probably wouldn't be the first to report problems there since this is live for over a year now.

There are however some issues with exports in ETS. See https://community.home-assistant.io/t/knx-communication-issues/645191/9?u=farmio If you experience one of those, please report it to KNXA.

**Comment by indivliving** [comment]
I think i would be great if there is a hint, if changes on the KNX Project are made (new devices etc.), than you have to upload a **new** exported .knxkeys file, even if no changes are made on other devices.
In my opinion, this behavior is not entirely clear, and would have saved me hours of work if I had known this.
But for now, everything works and we can close this issue.

**Comment by indivliving** [comment]
Unfortunately, I still have a problem with the communication with the KNX bus. I don't know if it still has to do with KNX Secure.
There are often no telegrams arriving in the Home Assistant. I have a few motion detectors and it is noticeable here. Often the "ON" or "OFF" telegram does not arrive. But in principle it works. (6 out of 10 times)
All telegrams are visible in the group monitor. Nothing is visible in the HA monitor. There are no error messages in the log.

**Comment by farmio** [comment]
I'm sorry to hear that, but there is not really any information in your post to help you further.
When telegrams don't reach HA the most common cause are filter table issues. Especially if the connection is stable, no DataSecure is involved and no log messages appear.

**Comment by indivliving** [comment]
Filter table is correct. Data Secure is on and working without errors in log. As I say, most of the time it works, but sometimes the telegrams do not reach HA...
